# Generated by Django 3.0.7 on 2020-12-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201228_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='demo',
            field=models.CharField(default='hhh', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='github',
            field=models.CharField(default='hh', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='hh', max_length=60),
            preserve_default=False,
        ),
    ]
